include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - prefer_const_constructors
    - prefer_const_literals_to_create_immutables
    - prefer_const_declarations
    - avoid_unnecessary_containers
    - use_key_in_widget_constructors
    - prefer_final_fields
    - unnecessary_this
    - unnecessary_new
    - avoid_print
    - prefer_is_empty
    - prefer_is_not_empty
    - avoid_redundant_argument_values
    - prefer_if_null_operators
    - prefer_null_aware_operators
    - sort_child_properties_last
    - use_build_context_synchronously
    - avoid_web_libraries_in_flutter

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore
  language:
    strict-casts: true
    strict-inference: true